#ifndef OCALLS_READER_H
#define OCALLS_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct report_table *report_table_t;
typedef struct report_table *report_mutable_table_t;
typedef const flatbuffers_uoffset_t *report_vec_t;
typedef flatbuffers_uoffset_t *report_mutable_vec_t;
typedef const struct pubkey_table *pubkey_table_t;
typedef struct pubkey_table *pubkey_mutable_table_t;
typedef const flatbuffers_uoffset_t *pubkey_vec_t;
typedef flatbuffers_uoffset_t *pubkey_mutable_vec_t;
typedef const struct encl_message_t_table *encl_message_t_table_t;
typedef struct encl_message_t_table *encl_message_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *encl_message_t_vec_t;
typedef flatbuffers_uoffset_t *encl_message_t_mutable_vec_t;
typedef const struct __pointer_flatbuffers_int8_table *__pointer_flatbuffers_int8_table_t;
typedef struct __pointer_flatbuffers_int8_table *__pointer_flatbuffers_int8_mutable_table_t;
typedef const flatbuffers_uoffset_t *__pointer_flatbuffers_int8_vec_t;
typedef flatbuffers_uoffset_t *__pointer_flatbuffers_int8_mutable_vec_t;
typedef const struct __pointer_pubkey_table *__pointer_pubkey_table_t;
typedef struct __pointer_pubkey_table *__pointer_pubkey_mutable_table_t;
typedef const flatbuffers_uoffset_t *__pointer_pubkey_vec_t;
typedef flatbuffers_uoffset_t *__pointer_pubkey_mutable_vec_t;
typedef const struct __ocall_wrapper_calc_message_table *__ocall_wrapper_calc_message_table_t;
typedef struct __ocall_wrapper_calc_message_table *__ocall_wrapper_calc_message_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_calc_message_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_calc_message_mutable_vec_t;
typedef const struct __ocall_wrapper_end_enclave_table *__ocall_wrapper_end_enclave_table_t;
typedef struct __ocall_wrapper_end_enclave_table *__ocall_wrapper_end_enclave_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_end_enclave_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_end_enclave_mutable_vec_t;
typedef const struct __ocall_wrapper_get_attestation_report_table *__ocall_wrapper_get_attestation_report_table_t;
typedef struct __ocall_wrapper_get_attestation_report_table *__ocall_wrapper_get_attestation_report_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_get_attestation_report_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_get_attestation_report_mutable_vec_t;
typedef const struct __ocall_wrapper_print_buffer_table *__ocall_wrapper_print_buffer_table_t;
typedef struct __ocall_wrapper_print_buffer_table *__ocall_wrapper_print_buffer_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_print_buffer_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_print_buffer_mutable_vec_t;
typedef const struct __ocall_wrapper_print_value_table *__ocall_wrapper_print_value_table_t;
typedef struct __ocall_wrapper_print_value_table *__ocall_wrapper_print_value_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_print_value_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_print_value_mutable_vec_t;
typedef const struct __ocall_wrapper_set_client_pk_table *__ocall_wrapper_set_client_pk_table_t;
typedef struct __ocall_wrapper_set_client_pk_table *__ocall_wrapper_set_client_pk_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_set_client_pk_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_set_client_pk_mutable_vec_t;
#ifndef report_identifier
#define report_identifier flatbuffers_identifier
#endif
#define report_type_hash ((flatbuffers_thash_t)0x19bb34eb)
#define report_type_identifier "\xeb\x34\xbb\x19"
#ifndef pubkey_identifier
#define pubkey_identifier flatbuffers_identifier
#endif
#define pubkey_type_hash ((flatbuffers_thash_t)0xdce48243)
#define pubkey_type_identifier "\x43\x82\xe4\xdc"
#ifndef encl_message_t_identifier
#define encl_message_t_identifier flatbuffers_identifier
#endif
#define encl_message_t_type_hash ((flatbuffers_thash_t)0x834657e6)
#define encl_message_t_type_identifier "\xe6\x57\x46\x83"
#ifndef __pointer_flatbuffers_int8_identifier
#define __pointer_flatbuffers_int8_identifier flatbuffers_identifier
#endif
#define __pointer_flatbuffers_int8_type_hash ((flatbuffers_thash_t)0x9b4a4145)
#define __pointer_flatbuffers_int8_type_identifier "\x45\x41\x4a\x9b"
#ifndef __pointer_pubkey_identifier
#define __pointer_pubkey_identifier flatbuffers_identifier
#endif
#define __pointer_pubkey_type_hash ((flatbuffers_thash_t)0x98214733)
#define __pointer_pubkey_type_identifier "\x33\x47\x21\x98"
#ifndef __ocall_wrapper_calc_message_identifier
#define __ocall_wrapper_calc_message_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_calc_message_type_hash ((flatbuffers_thash_t)0x8fa287c8)
#define __ocall_wrapper_calc_message_type_identifier "\xc8\x87\xa2\x8f"
#ifndef __ocall_wrapper_end_enclave_identifier
#define __ocall_wrapper_end_enclave_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_end_enclave_type_hash ((flatbuffers_thash_t)0xa7b40b13)
#define __ocall_wrapper_end_enclave_type_identifier "\x13\x0b\xb4\xa7"
#ifndef __ocall_wrapper_get_attestation_report_identifier
#define __ocall_wrapper_get_attestation_report_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_get_attestation_report_type_hash ((flatbuffers_thash_t)0x94810825)
#define __ocall_wrapper_get_attestation_report_type_identifier "\x25\x08\x81\x94"
#ifndef __ocall_wrapper_print_buffer_identifier
#define __ocall_wrapper_print_buffer_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_print_buffer_type_hash ((flatbuffers_thash_t)0xefef7b8b)
#define __ocall_wrapper_print_buffer_type_identifier "\x8b\x7b\xef\xef"
#ifndef __ocall_wrapper_print_value_identifier
#define __ocall_wrapper_print_value_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_print_value_type_hash ((flatbuffers_thash_t)0xd935caba)
#define __ocall_wrapper_print_value_type_identifier "\xba\xca\x35\xd9"
#ifndef __ocall_wrapper_set_client_pk_identifier
#define __ocall_wrapper_set_client_pk_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_set_client_pk_type_hash ((flatbuffers_thash_t)0xe644a765)
#define __ocall_wrapper_set_client_pk_type_identifier "\x65\xa7\x44\xe6"



struct report_table { uint8_t unused__; };

static inline size_t report_vec_len(report_vec_t vec)
__flatbuffers_vec_len(vec)
static inline report_table_t report_vec_at(report_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(report_table_t, vec, i, 0)
__flatbuffers_table_as_root(report)

__flatbuffers_define_vector_field(0, report, data, flatbuffers_int8_vec_t, 0)

struct pubkey_table { uint8_t unused__; };

static inline size_t pubkey_vec_len(pubkey_vec_t vec)
__flatbuffers_vec_len(vec)
static inline pubkey_table_t pubkey_vec_at(pubkey_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(pubkey_table_t, vec, i, 0)
__flatbuffers_table_as_root(pubkey)

__flatbuffers_define_vector_field(0, pubkey, data, flatbuffers_int8_vec_t, 0)

struct encl_message_t_table { uint8_t unused__; };

static inline size_t encl_message_t_vec_len(encl_message_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline encl_message_t_table_t encl_message_t_vec_at(encl_message_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(encl_message_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(encl_message_t)

__flatbuffers_define_vector_field(0, encl_message_t, host_ptr, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, encl_message_t, len, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct __pointer_flatbuffers_int8_table { uint8_t unused__; };

static inline size_t __pointer_flatbuffers_int8_vec_len(__pointer_flatbuffers_int8_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __pointer_flatbuffers_int8_table_t __pointer_flatbuffers_int8_vec_at(__pointer_flatbuffers_int8_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__pointer_flatbuffers_int8_table_t, vec, i, 0)
__flatbuffers_table_as_root(__pointer_flatbuffers_int8)

__flatbuffers_define_scalar_field(0, __pointer_flatbuffers_int8, __is_null, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, __pointer_flatbuffers_int8, __data, flatbuffers_int8, int8_t, INT8_C(0))

struct __pointer_pubkey_table { uint8_t unused__; };

static inline size_t __pointer_pubkey_vec_len(__pointer_pubkey_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __pointer_pubkey_table_t __pointer_pubkey_vec_at(__pointer_pubkey_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__pointer_pubkey_table_t, vec, i, 0)
__flatbuffers_table_as_root(__pointer_pubkey)

__flatbuffers_define_scalar_field(0, __pointer_pubkey, __is_null, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_table_field(1, __pointer_pubkey, __data, pubkey_table_t, 0)

struct __ocall_wrapper_calc_message_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_calc_message_vec_len(__ocall_wrapper_calc_message_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_calc_message_table_t __ocall_wrapper_calc_message_vec_at(__ocall_wrapper_calc_message_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_calc_message_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_calc_message)

__flatbuffers_define_table_field(0, __ocall_wrapper_calc_message, msg, encl_message_t_table_t, 0)
__flatbuffers_define_table_field(1, __ocall_wrapper_calc_message, __return_value, encl_message_t_table_t, 0)

struct __ocall_wrapper_end_enclave_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_end_enclave_vec_len(__ocall_wrapper_end_enclave_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_end_enclave_table_t __ocall_wrapper_end_enclave_vec_at(__ocall_wrapper_end_enclave_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_end_enclave_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_end_enclave)

__flatbuffers_define_scalar_field(0, __ocall_wrapper_end_enclave, __return_value, flatbuffers_int8, int8_t, INT8_C(0))

struct __ocall_wrapper_get_attestation_report_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_get_attestation_report_vec_len(__ocall_wrapper_get_attestation_report_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_get_attestation_report_table_t __ocall_wrapper_get_attestation_report_vec_at(__ocall_wrapper_get_attestation_report_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_get_attestation_report_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_get_attestation_report)

__flatbuffers_define_table_field(0, __ocall_wrapper_get_attestation_report, __return_value, report_table_t, 0)

struct __ocall_wrapper_print_buffer_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_print_buffer_vec_len(__ocall_wrapper_print_buffer_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_print_buffer_table_t __ocall_wrapper_print_buffer_vec_at(__ocall_wrapper_print_buffer_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_print_buffer_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_print_buffer)

__flatbuffers_define_vector_field(0, __ocall_wrapper_print_buffer, str, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, __ocall_wrapper_print_buffer, __return_value, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct __ocall_wrapper_print_value_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_print_value_vec_len(__ocall_wrapper_print_value_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_print_value_table_t __ocall_wrapper_print_value_vec_at(__ocall_wrapper_print_value_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_print_value_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_print_value)

__flatbuffers_define_scalar_field(0, __ocall_wrapper_print_value, val, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, __ocall_wrapper_print_value, __return_value, flatbuffers_int8, int8_t, INT8_C(0))

struct __ocall_wrapper_set_client_pk_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_set_client_pk_vec_len(__ocall_wrapper_set_client_pk_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_set_client_pk_table_t __ocall_wrapper_set_client_pk_vec_at(__ocall_wrapper_set_client_pk_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_set_client_pk_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_set_client_pk)

__flatbuffers_define_table_field(0, __ocall_wrapper_set_client_pk, pk, __pointer_pubkey_table_t, 0)
__flatbuffers_define_scalar_field(1, __ocall_wrapper_set_client_pk, __return_value, flatbuffers_int32, int32_t, INT32_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* OCALLS_READER_H */
