#ifndef OCALLS_READER_H
#define OCALLS_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct pubkey_table *pubkey_table_t;
typedef struct pubkey_table *pubkey_mutable_table_t;
typedef const flatbuffers_uoffset_t *pubkey_vec_t;
typedef flatbuffers_uoffset_t *pubkey_mutable_vec_t;
typedef const struct encl_message_t_table *encl_message_t_table_t;
typedef struct encl_message_t_table *encl_message_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *encl_message_t_vec_t;
typedef flatbuffers_uoffset_t *encl_message_t_mutable_vec_t;
typedef const struct __pointer_flatbuffers_int8_table *__pointer_flatbuffers_int8_table_t;
typedef struct __pointer_flatbuffers_int8_table *__pointer_flatbuffers_int8_mutable_table_t;
typedef const flatbuffers_uoffset_t *__pointer_flatbuffers_int8_vec_t;
typedef flatbuffers_uoffset_t *__pointer_flatbuffers_int8_mutable_vec_t;
typedef const struct __pointer_pubkey_table *__pointer_pubkey_table_t;
typedef struct __pointer_pubkey_table *__pointer_pubkey_mutable_table_t;
typedef const flatbuffers_uoffset_t *__pointer_pubkey_vec_t;
typedef flatbuffers_uoffset_t *__pointer_pubkey_mutable_vec_t;
typedef const struct __ocall_wrapper_print_buffer_table *__ocall_wrapper_print_buffer_table_t;
typedef struct __ocall_wrapper_print_buffer_table *__ocall_wrapper_print_buffer_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_print_buffer_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_print_buffer_mutable_vec_t;
typedef const struct __ocall_wrapper_print_value_table *__ocall_wrapper_print_value_table_t;
typedef struct __ocall_wrapper_print_value_table *__ocall_wrapper_print_value_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_print_value_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_print_value_mutable_vec_t;
typedef const struct __ocall_wrapper_send_reply_table *__ocall_wrapper_send_reply_table_t;
typedef struct __ocall_wrapper_send_reply_table *__ocall_wrapper_send_reply_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_send_reply_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_send_reply_mutable_vec_t;
typedef const struct __ocall_wrapper_send_report_table *__ocall_wrapper_send_report_table_t;
typedef struct __ocall_wrapper_send_report_table *__ocall_wrapper_send_report_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_send_report_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_send_report_mutable_vec_t;
typedef const struct __ocall_wrapper_wait_for_client_pubkey_table *__ocall_wrapper_wait_for_client_pubkey_table_t;
typedef struct __ocall_wrapper_wait_for_client_pubkey_table *__ocall_wrapper_wait_for_client_pubkey_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_wait_for_client_pubkey_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_wait_for_client_pubkey_mutable_vec_t;
typedef const struct __ocall_wrapper_wait_for_message_table *__ocall_wrapper_wait_for_message_table_t;
typedef struct __ocall_wrapper_wait_for_message_table *__ocall_wrapper_wait_for_message_mutable_table_t;
typedef const flatbuffers_uoffset_t *__ocall_wrapper_wait_for_message_vec_t;
typedef flatbuffers_uoffset_t *__ocall_wrapper_wait_for_message_mutable_vec_t;
#ifndef pubkey_identifier
#define pubkey_identifier flatbuffers_identifier
#endif
#define pubkey_type_hash ((flatbuffers_thash_t)0xdce48243)
#define pubkey_type_identifier "\x43\x82\xe4\xdc"
#ifndef encl_message_t_identifier
#define encl_message_t_identifier flatbuffers_identifier
#endif
#define encl_message_t_type_hash ((flatbuffers_thash_t)0x834657e6)
#define encl_message_t_type_identifier "\xe6\x57\x46\x83"
#ifndef __pointer_flatbuffers_int8_identifier
#define __pointer_flatbuffers_int8_identifier flatbuffers_identifier
#endif
#define __pointer_flatbuffers_int8_type_hash ((flatbuffers_thash_t)0x9b4a4145)
#define __pointer_flatbuffers_int8_type_identifier "\x45\x41\x4a\x9b"
#ifndef __pointer_pubkey_identifier
#define __pointer_pubkey_identifier flatbuffers_identifier
#endif
#define __pointer_pubkey_type_hash ((flatbuffers_thash_t)0x98214733)
#define __pointer_pubkey_type_identifier "\x33\x47\x21\x98"
#ifndef __ocall_wrapper_print_buffer_identifier
#define __ocall_wrapper_print_buffer_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_print_buffer_type_hash ((flatbuffers_thash_t)0xefef7b8b)
#define __ocall_wrapper_print_buffer_type_identifier "\x8b\x7b\xef\xef"
#ifndef __ocall_wrapper_print_value_identifier
#define __ocall_wrapper_print_value_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_print_value_type_hash ((flatbuffers_thash_t)0xd935caba)
#define __ocall_wrapper_print_value_type_identifier "\xba\xca\x35\xd9"
#ifndef __ocall_wrapper_send_reply_identifier
#define __ocall_wrapper_send_reply_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_send_reply_type_hash ((flatbuffers_thash_t)0xc6dac4f4)
#define __ocall_wrapper_send_reply_type_identifier "\xf4\xc4\xda\xc6"
#ifndef __ocall_wrapper_send_report_identifier
#define __ocall_wrapper_send_report_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_send_report_type_hash ((flatbuffers_thash_t)0x58e07d6a)
#define __ocall_wrapper_send_report_type_identifier "\x6a\x7d\xe0\x58"
#ifndef __ocall_wrapper_wait_for_client_pubkey_identifier
#define __ocall_wrapper_wait_for_client_pubkey_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_wait_for_client_pubkey_type_hash ((flatbuffers_thash_t)0xe0772539)
#define __ocall_wrapper_wait_for_client_pubkey_type_identifier "\x39\x25\x77\xe0"
#ifndef __ocall_wrapper_wait_for_message_identifier
#define __ocall_wrapper_wait_for_message_identifier flatbuffers_identifier
#endif
#define __ocall_wrapper_wait_for_message_type_hash ((flatbuffers_thash_t)0x6c536324)
#define __ocall_wrapper_wait_for_message_type_identifier "\x24\x63\x53\x6c"



struct pubkey_table { uint8_t unused__; };

static inline size_t pubkey_vec_len(pubkey_vec_t vec)
__flatbuffers_vec_len(vec)
static inline pubkey_table_t pubkey_vec_at(pubkey_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(pubkey_table_t, vec, i, 0)
__flatbuffers_table_as_root(pubkey)

__flatbuffers_define_vector_field(0, pubkey, data, flatbuffers_int8_vec_t, 0)

struct encl_message_t_table { uint8_t unused__; };

static inline size_t encl_message_t_vec_len(encl_message_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline encl_message_t_table_t encl_message_t_vec_at(encl_message_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(encl_message_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(encl_message_t)

__flatbuffers_define_vector_field(0, encl_message_t, host_ptr, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, encl_message_t, len, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct __pointer_flatbuffers_int8_table { uint8_t unused__; };

static inline size_t __pointer_flatbuffers_int8_vec_len(__pointer_flatbuffers_int8_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __pointer_flatbuffers_int8_table_t __pointer_flatbuffers_int8_vec_at(__pointer_flatbuffers_int8_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__pointer_flatbuffers_int8_table_t, vec, i, 0)
__flatbuffers_table_as_root(__pointer_flatbuffers_int8)

__flatbuffers_define_scalar_field(0, __pointer_flatbuffers_int8, __is_null, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, __pointer_flatbuffers_int8, __data, flatbuffers_int8, int8_t, INT8_C(0))

struct __pointer_pubkey_table { uint8_t unused__; };

static inline size_t __pointer_pubkey_vec_len(__pointer_pubkey_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __pointer_pubkey_table_t __pointer_pubkey_vec_at(__pointer_pubkey_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__pointer_pubkey_table_t, vec, i, 0)
__flatbuffers_table_as_root(__pointer_pubkey)

__flatbuffers_define_scalar_field(0, __pointer_pubkey, __is_null, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_table_field(1, __pointer_pubkey, __data, pubkey_table_t, 0)

struct __ocall_wrapper_print_buffer_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_print_buffer_vec_len(__ocall_wrapper_print_buffer_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_print_buffer_table_t __ocall_wrapper_print_buffer_vec_at(__ocall_wrapper_print_buffer_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_print_buffer_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_print_buffer)

__flatbuffers_define_vector_field(0, __ocall_wrapper_print_buffer, str, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, __ocall_wrapper_print_buffer, __return_value, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct __ocall_wrapper_print_value_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_print_value_vec_len(__ocall_wrapper_print_value_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_print_value_table_t __ocall_wrapper_print_value_vec_at(__ocall_wrapper_print_value_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_print_value_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_print_value)

__flatbuffers_define_scalar_field(0, __ocall_wrapper_print_value, val, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, __ocall_wrapper_print_value, __return_value, flatbuffers_int8, int8_t, INT8_C(0))

struct __ocall_wrapper_send_reply_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_send_reply_vec_len(__ocall_wrapper_send_reply_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_send_reply_table_t __ocall_wrapper_send_reply_vec_at(__ocall_wrapper_send_reply_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_send_reply_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_send_reply)

__flatbuffers_define_vector_field(0, __ocall_wrapper_send_reply, message, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, __ocall_wrapper_send_reply, len, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, __ocall_wrapper_send_reply, __return_value, flatbuffers_int8, int8_t, INT8_C(0))

struct __ocall_wrapper_send_report_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_send_report_vec_len(__ocall_wrapper_send_report_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_send_report_table_t __ocall_wrapper_send_report_vec_at(__ocall_wrapper_send_report_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_send_report_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_send_report)

__flatbuffers_define_vector_field(0, __ocall_wrapper_send_report, shared_buffer, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(1, __ocall_wrapper_send_report, len, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, __ocall_wrapper_send_report, __return_value, flatbuffers_int8, int8_t, INT8_C(0))

struct __ocall_wrapper_wait_for_client_pubkey_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_wait_for_client_pubkey_vec_len(__ocall_wrapper_wait_for_client_pubkey_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_wait_for_client_pubkey_table_t __ocall_wrapper_wait_for_client_pubkey_vec_at(__ocall_wrapper_wait_for_client_pubkey_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_wait_for_client_pubkey_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_wait_for_client_pubkey)

__flatbuffers_define_table_field(0, __ocall_wrapper_wait_for_client_pubkey, __return_value, __pointer_pubkey_table_t, 0)

struct __ocall_wrapper_wait_for_message_table { uint8_t unused__; };

static inline size_t __ocall_wrapper_wait_for_message_vec_len(__ocall_wrapper_wait_for_message_vec_t vec)
__flatbuffers_vec_len(vec)
static inline __ocall_wrapper_wait_for_message_table_t __ocall_wrapper_wait_for_message_vec_at(__ocall_wrapper_wait_for_message_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(__ocall_wrapper_wait_for_message_table_t, vec, i, 0)
__flatbuffers_table_as_root(__ocall_wrapper_wait_for_message)

__flatbuffers_define_table_field(0, __ocall_wrapper_wait_for_message, __return_value, encl_message_t_table_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* OCALLS_READER_H */
