#ifndef OCALLS_VERIFIER_H
#define OCALLS_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef OCALLS_READER_H
#include "ocalls_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int report_verify_table(flatcc_table_verifier_descriptor_t *td);
static int pubkey_verify_table(flatcc_table_verifier_descriptor_t *td);
static int encl_message_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __pointer_flatbuffers_int8_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __pointer_pubkey_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __ocall_wrapper_calc_message_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __ocall_wrapper_end_enclave_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __ocall_wrapper_get_attestation_report_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __ocall_wrapper_print_buffer_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __ocall_wrapper_print_value_verify_table(flatcc_table_verifier_descriptor_t *td);
static int __ocall_wrapper_set_client_pk_verify_table(flatcc_table_verifier_descriptor_t *td);

static int report_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 1, 1, INT64_C(4294967295)) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int report_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, report_identifier, &report_verify_table);
}

static inline int report_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, report_type_identifier, &report_verify_table);
}

static inline int report_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &report_verify_table);
}

static inline int report_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &report_verify_table);
}

static int pubkey_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 1, 1, INT64_C(4294967295)) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int pubkey_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, pubkey_identifier, &pubkey_verify_table);
}

static inline int pubkey_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, pubkey_type_identifier, &pubkey_verify_table);
}

static inline int pubkey_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &pubkey_verify_table);
}

static inline int pubkey_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &pubkey_verify_table);
}

static int encl_message_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 1, 1, INT64_C(4294967295)) /* host_ptr */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* len */)) return ret;
    return flatcc_verify_ok;
}

static inline int encl_message_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, encl_message_t_identifier, &encl_message_t_verify_table);
}

static inline int encl_message_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, encl_message_t_type_identifier, &encl_message_t_verify_table);
}

static inline int encl_message_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &encl_message_t_verify_table);
}

static inline int encl_message_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &encl_message_t_verify_table);
}

static int __pointer_flatbuffers_int8_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* __is_null */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* __data */)) return ret;
    return flatcc_verify_ok;
}

static inline int __pointer_flatbuffers_int8_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __pointer_flatbuffers_int8_identifier, &__pointer_flatbuffers_int8_verify_table);
}

static inline int __pointer_flatbuffers_int8_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __pointer_flatbuffers_int8_type_identifier, &__pointer_flatbuffers_int8_verify_table);
}

static inline int __pointer_flatbuffers_int8_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__pointer_flatbuffers_int8_verify_table);
}

static inline int __pointer_flatbuffers_int8_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__pointer_flatbuffers_int8_verify_table);
}

static int __pointer_pubkey_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* __is_null */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &pubkey_verify_table) /* __data */)) return ret;
    return flatcc_verify_ok;
}

static inline int __pointer_pubkey_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __pointer_pubkey_identifier, &__pointer_pubkey_verify_table);
}

static inline int __pointer_pubkey_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __pointer_pubkey_type_identifier, &__pointer_pubkey_verify_table);
}

static inline int __pointer_pubkey_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__pointer_pubkey_verify_table);
}

static inline int __pointer_pubkey_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__pointer_pubkey_verify_table);
}

static int __ocall_wrapper_calc_message_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &encl_message_t_verify_table) /* msg */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &encl_message_t_verify_table) /* __return_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int __ocall_wrapper_calc_message_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_calc_message_identifier, &__ocall_wrapper_calc_message_verify_table);
}

static inline int __ocall_wrapper_calc_message_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_calc_message_type_identifier, &__ocall_wrapper_calc_message_verify_table);
}

static inline int __ocall_wrapper_calc_message_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__ocall_wrapper_calc_message_verify_table);
}

static inline int __ocall_wrapper_calc_message_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__ocall_wrapper_calc_message_verify_table);
}

static int __ocall_wrapper_end_enclave_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* __return_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int __ocall_wrapper_end_enclave_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_end_enclave_identifier, &__ocall_wrapper_end_enclave_verify_table);
}

static inline int __ocall_wrapper_end_enclave_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_end_enclave_type_identifier, &__ocall_wrapper_end_enclave_verify_table);
}

static inline int __ocall_wrapper_end_enclave_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__ocall_wrapper_end_enclave_verify_table);
}

static inline int __ocall_wrapper_end_enclave_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__ocall_wrapper_end_enclave_verify_table);
}

static int __ocall_wrapper_get_attestation_report_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &report_verify_table) /* __return_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int __ocall_wrapper_get_attestation_report_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_get_attestation_report_identifier, &__ocall_wrapper_get_attestation_report_verify_table);
}

static inline int __ocall_wrapper_get_attestation_report_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_get_attestation_report_type_identifier, &__ocall_wrapper_get_attestation_report_verify_table);
}

static inline int __ocall_wrapper_get_attestation_report_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__ocall_wrapper_get_attestation_report_verify_table);
}

static inline int __ocall_wrapper_get_attestation_report_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__ocall_wrapper_get_attestation_report_verify_table);
}

static int __ocall_wrapper_print_buffer_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 1, 1, INT64_C(4294967295)) /* str */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* __return_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int __ocall_wrapper_print_buffer_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_print_buffer_identifier, &__ocall_wrapper_print_buffer_verify_table);
}

static inline int __ocall_wrapper_print_buffer_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_print_buffer_type_identifier, &__ocall_wrapper_print_buffer_verify_table);
}

static inline int __ocall_wrapper_print_buffer_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__ocall_wrapper_print_buffer_verify_table);
}

static inline int __ocall_wrapper_print_buffer_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__ocall_wrapper_print_buffer_verify_table);
}

static int __ocall_wrapper_print_value_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* val */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* __return_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int __ocall_wrapper_print_value_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_print_value_identifier, &__ocall_wrapper_print_value_verify_table);
}

static inline int __ocall_wrapper_print_value_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_print_value_type_identifier, &__ocall_wrapper_print_value_verify_table);
}

static inline int __ocall_wrapper_print_value_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__ocall_wrapper_print_value_verify_table);
}

static inline int __ocall_wrapper_print_value_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__ocall_wrapper_print_value_verify_table);
}

static int __ocall_wrapper_set_client_pk_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &__pointer_pubkey_verify_table) /* pk */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* __return_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int __ocall_wrapper_set_client_pk_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_set_client_pk_identifier, &__ocall_wrapper_set_client_pk_verify_table);
}

static inline int __ocall_wrapper_set_client_pk_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, __ocall_wrapper_set_client_pk_type_identifier, &__ocall_wrapper_set_client_pk_verify_table);
}

static inline int __ocall_wrapper_set_client_pk_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__ocall_wrapper_set_client_pk_verify_table);
}

static inline int __ocall_wrapper_set_client_pk_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__ocall_wrapper_set_client_pk_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* OCALLS_VERIFIER_H */
